### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by therobinkim**

### CODE REVIEW

**Comment by therobinkim** [comment]
Closing this PR as the repo is no longer being maintained.

**Comment by geoffreymcgill** [comment]
Hello. This pr can be merged, but signing CLA is required by submitting [Contributor License Agreement Form](http://goo.gl/forms/2NxnVYI3tK).

https://github.com/datejs/Datejs/blob/master/CONTRIBUTING.md

**Comment by therobinkim** [comment]
@geoffreymcgill CLA signed!

**Comment by geoffreymcgill** [comment]
Hi @therobinkim – I think you're the only one that can reopen the pr.

**Comment by therobinkim** [comment]
image

@geoffreymcgill Ah... I deleted my fork a while ago, so I guess I can't reopen it. I will recreate a new PR if I have a chance, otherwise a-okay with me if somebody else decides to call dibs on the proposed change!

**Comment by OppenheimerAndTheMartians** [comment]
@geoffreymcgill CLA signed!

**Pull request closed without merging**
