### PR TITLE
Add bower.json.

### PR DESCRIPTION
**Pull request by wangchj**

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hi @wangchj. I am reviewing your pull request. 

Before acceptance, we would need the [CLA](https://github.com/datejs/Datejs/blob/master/CLA.md) signed. You can view our [CONTRIBUTING](https://github.com/datejs/Datejs/blob/master/CONTRIBUTING.md) document, then if acceptable, sign the CLA using the [Contribution License Agreement Acceptance Form](http://goo.gl/forms/2NxnVYI3tK).

**Comment by vovafeldman** [comment]
Maybe it's me, but I think bower's package.json is missing of:
```js
"main": "build/date.js",
```

I have an automated gulp task that concatenates all my bower JS libs, but since your package doesn't include the "main" property, it fails to identify the main file. Thanks!

**Comment by geoffreymcgill** [comment]
CLA has not been signed. Closing issue.

**Comment by vovafeldman** [comment]
@geoffreymcgill is the CLA meant for me?

**Comment by geoffreymcgill** [comment]
Hi @vovafeldman – Just @wangchj, who is the only code author (Contributor) in this pull request.

**Comment by tracker1** [comment]
A mild suggestion, would be a postversion script (assuming you use npm version commands) that will sync the bower version with the one in package.json.

**Comment by geoffreymcgill** [comment]
CLA not signed, so closing this PR for now.

**Comment by chrisdrackett** [comment]
this is the most ridiculous thing I've ever seen on GitHub.

**Comment by geoffreymcgill** [comment]
> @chrisdrackett this is the most ridiculous thing I've ever seen on GitHub.

why?

**Comment by chrisdrackett** [comment]
I'm just surprised this library never made it onto NPM because someone didn't sign a CLA for "code" that isn't at all proprietary or novel.

**Comment by geoffreymcgill** [comment]
Unsure. I never looked at the PR since the CLA was requested and no acceptance was provided.

**Pull request closed without merging**
