### PR TITLE
Support abbreviated german weekdays

### PR DESCRIPTION
**Pull request by thomastrethan**
see https://bugs.horde.org/ticket/14242

### CODE REVIEW

**Comment by yunosh** [comment]
FWIW I would also support three-letter-abbreviations like the English locales, i.e. /^mo(n(day)?)?/

**Comment by thomastrethan** [comment]
I think three-letter-abbreviations are quite uncommon in German (as far as I know, at least in Austria), that's why I only added the two-letter-ones...

**Comment by yunosh** [comment]
Yes, they are uncommon, but it doesn't hurt checking for them either.

**Comment by geoffreymcgill** [comment]
CLA has not been signed. Closing issue.

**Comment by thomastrethan** [comment]
Sorry, I missed the part for signing the CLA. Unfortunately I'm unable to sign it, found https://cla.github.com/agreement but no option for signing... please help, thx.

**Comment by thomastrethan** [comment]
Finally found http://goo.gl/forms/2NxnVYI3tK and submitted it, I hope that's ok now. Can we re-open?

**Comment by geoffreymcgill** [comment]
Thanks for signing. 

I will re-open and review pr. 

I'm looking into stream lining the CLA process. Looks like there's some new services that I was not aware of previously, such as [CLA Assistant](https://github.com/integrations/cla-assistant).

**Review by geoffreymcgill — COMMENTED** [review]
Looks great! Thanks for submitting this improvement.

**Comment by thomastrethan** [comment]
Thanks, glad it'll make it ;-)

**Pull request merged**
