### PR TITLE
Fix parsing of French dates by modifying regex patterns for months and days

### PR DESCRIPTION
**Pull request by attaboy**
Date.parse('10 juillet 2013') and various other variants fails in current version of Datejs. These patches modify the regexes so that parsing works correctly.

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hello @attaboy, 

Thanks for the Datejs Pull Request. 

Before accepting a Pull Request, an accepted [CLA](https://github.com/datejs/Datejs/blob/master/CLA.md) is required. More information is available in [CONTRINUTING](https://github.com/datejs/Datejs/blob/master/CONTRIBUTING.md#submitting-changes).

The CLA can be accepted by submitting the [Contributor License Agreement](http://goo.gl/forms/2NxnVYI3tK) form.

Once the CLA form has been accepted by contributing authors of this Pull Request, the pr will be fully reviewed and likely merged into the repo.

Please let me know if you have any questions.

**Comment by geoffreymcgill** [comment]
CLA has not been signed. Closing issue.

**Comment by attaboy** [comment]
I'm not sure why it's complaining about me not being a GitHub user, although it's possible I committed this code from a work email address in 2013 that I no longer own. In any case, I've signed the CLA (as far as I can tell).

**Comment by geoffreymcgill** [comment]
> I committed this code from a work email address in 2013 that I no longer own

Yes, that appears to be the case. Seems like it's associating the pr to your email address. 

<a href="https://github.com/datejs/Datejs/pull/14/commits/63f63c33f4162e0f3ad2c8ea302d032933f05180">screenshot 2017-01-11 09 40 50</a>

If you hover over the **(?)** in the commit [details](https://github.com/datejs/Datejs/pull/14/commits/63f63c33f4162e0f3ad2c8ea302d032933f05180), you can see the email address associated to this commit.

I can see that @attaboy has signed the CLA.

**Comment by attaboy** [comment]
Curious. I don't see the (?) icon, nor any other way to see the commit details. In 2013 I worked at Twitter so it would probably have been la@twitter.com. IIRC we were using the library at the time.

**Comment by geoffreymcgill** [comment]
Double checked, and looks like the (?) is only available to repo admins. It was the twitter.com email address.

**Pull request merged**
